# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: 'Prometheus'
  type: 'prometheus'
  access: 'proxy'
  org_id: 1
  url: 'http://prometheus:9090'
  is_default: true
  version: 1
  editable: true

- name: 'ClickHouse'
  type: 'grafana-clickhouse-datasource'
  isDefault: true
  jsonData:
    defaultDatabase: r0
    port: 9000
    server: clickhouse-0.localhost
    username: demouser
    tlsSkipVerify: false
  secureJsonData:
    password: '239QV8JkGmF9AZM'
  editable: true
